<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    public function getIncrementing()
    {
//        return parent::getIncrementing(); // TODO: Change the autogenerated stub
        return false;
    }

    public function getKeyType()
    {
//        return parent::getKeyType(); // TODO: Change the autogenerated stub
        return 'string';
    }

}
